# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [2]:
import sys
print(sys.executable)

/Library/Frameworks/Python.framework/Versions/3.13/bin/python3

In [3]:
%pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd
print(pd.__version__)

3.0.5

In [5]:
import sys
print(sys.executable)

/Library/Frameworks/Python.framework/Versions/3.13/bin/python3

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [17]:
import pandas as pd

In [18]:
df = pd.read_csv("file1.csv")

df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [19]:
print("Original number of rows:", df.shape[0])
print("Original number of columns:", df.shape[1])

print("\nOriginal column names:")
print(df.columns.tolist())

Original number of rows: 4008
Original number of columns: 11

Original column names:
['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value', 'Income', 'Monthly Premium Auto', 'Number of Open Complaints', 'Policy Type', 'Vehicle Class', 'Total Claim Amount']

In [ ]:
The original dataset contains 4,008 rows and 11 columns. The columns include customer identification, location, demographic information, policy information, income, premiums, complaints, and claim amounts.

In [20]:
completely_empty_rows = df.isna().all(axis=1).sum()

print("Completely empty rows:", completely_empty_rows)

Completely empty rows: 2937

In [ ]:
The dataset contains 2,937 completely empty rows. These rows do not contain any customer information.

In [21]:
df = df.dropna(how="all").reset_index(drop=True)

print("Rows after removing empty rows:", df.shape[0])
print("Columns after removing empty rows:", df.shape[1])

Rows after removing empty rows: 1071
Columns after removing empty rows: 11

In [ ]:
After removing rows where every value is missing, the dataset contains 1,071 valid customer records and 11 columns. Only completely empty rows were removed.

In [22]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
)

print(df.columns.tolist())

['customer', 'st', 'gender', 'education', 'customer_lifetime_value', 'income', 'monthly_premium_auto', 'number_of_open_complaints', 'policy_type', 'vehicle_class', 'total_claim_amount']

In [ ]:
The column names were standardized by converting them to lowercase and replacing spaces with underscores. This makes the column names easier and more consistent to use in Python.

In [23]:
df.dtypes

customer                         str
st                               str
gender                           str
education                        str
customer_lifetime_value          str
income                       float64
monthly_premium_auto         float64
number_of_open_complaints        str
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

In [ ]:
The dataset contains both categorical and numerical variables. Customer, state, gender, education, policy type, and vehicle class are stored as text. Income, monthly premium auto, and total claim amount are numerical. Customer lifetime value and number of open complaints require further attention because they are stored as text.

In [24]:
data_type_assessment = pd.DataFrame({
    "current_data_type": df.dtypes.astype(str),
    "variable_type": [
        "Identifier",
        "Categorical",
        "Categorical",
        "Categorical",
        "Numerical",
        "Numerical",
        "Numerical",
        "Coded variable",
        "Categorical",
        "Categorical",
        "Numerical"
    ],
    "action_needed": [
        "No conversion needed",
        "No conversion needed",
        "No conversion needed",
        "No conversion needed",
        "Convert from text to numeric",
        "No conversion needed",
        "No conversion needed",
        "Requires cleaning and interpretation",
        "No conversion needed",
        "No conversion needed",
        "No conversion needed"
    ]
})

data_type_assessment

,current_data_type,variable_type,action_needed
customer,str,Identifier,No conversion needed
st,str,Categorical,No conversion needed
gender,str,Categorical,No conversion needed
education,str,Categorical,No conversion needed
customer_lifetime_value,str,Numerical,Convert from text to numeric
income,float64,Numerical,No conversion needed
monthly_premium_auto,float64,Numerical,No conversion needed
number_of_open_complaints,str,Coded variable,Requires cleaning and interpretation
policy_type,str,Categorical,No conversion needed
vehicle_class,str,Categorical,No conversion needed
total_claim_amount,float64,Numerical,No conversion needed

In [ ]:
Customer lifetime value has an incorrect data type because it contains percent signs and is stored as text. It should be converted to a numerical column. Number of open complaints also contains slash-separated values such as 1/0/00, so it should not be converted directly until the meaning of each part is confirmed.

In [25]:
df["customer_lifetime_value"] = (
    df["customer_lifetime_value"]
    .astype("string")
    .str.replace("%", "", regex=False)
)

df["customer_lifetime_value"] = pd.to_numeric(
    df["customer_lifetime_value"],
    errors="coerce"
)

In [26]:
print(
    "Customer lifetime value data type:",
    df["customer_lifetime_value"].dtype
)

print(
    "Missing customer lifetime values:",
    df["customer_lifetime_value"].isna().sum()
)

df["customer_lifetime_value"].head()

Customer lifetime value data type: Float64
Missing customer lifetime values: 3

0          <NA>
1     697953.59
2    1288743.17
3     764586.18
4     536307.65
Name: customer_lifetime_value, dtype: Float64

In [ ]:
Customer lifetime value was successfully converted from text to a numerical float64 column. The percent signs were removed, and missing or invalid values were converted to NaN.

In [27]:
unique_value_counts = df.nunique()

unique_value_counts

customer                     1071
st                              8
gender                          5
education                       6
customer_lifetime_value      1027
income                        774
monthly_premium_auto          132
number_of_open_complaints       6
policy_type                     3
vehicle_class                   6
total_claim_amount            761
dtype: int64

In [ ]:
The customer column contains 1,071 unique values because it is an identification field. State, gender, education, policy type, and vehicle class contain fewer unique values and are categorical variables. The numerical columns contain many distinct values.

In [28]:
categorical_columns = [
    "st",
    "gender",
    "education",
    "policy_type",
    "vehicle_class"
]

numerical_columns = [
    "customer_lifetime_value",
    "income",
    "monthly_premium_auto",
    "total_claim_amount"
]

print("Categorical columns:")
print(categorical_columns)

print("\nNumerical columns:")
print(numerical_columns)

Categorical columns:
['st', 'gender', 'education', 'policy_type', 'vehicle_class']

Numerical columns:
['customer_lifetime_value', 'income', 'monthly_premium_auto', 'total_claim_amount']

In [ ]:
The categorical columns describe customer groups or classifications, while the numerical columns represent measurable amounts such as income, premiums, customer value, and claims.

In [29]:
for column in categorical_columns:
    print(f"\nUnique values in {column}:")
    print(df[column].dropna().unique())

Unique values in st:
<StringArray>
['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali', 'AZ',
 'WA']
Length: 8, dtype: str

Unique values in gender:
<StringArray>
['F', 'M', 'Femal', 'Male', 'female']
Length: 5, dtype: str

Unique values in education:
<StringArray>
['Master', 'Bachelor', 'High School or Below', 'College', 'Bachelors',
 'Doctor']
Length: 6, dtype: str

Unique values in policy_type:
<StringArray>
['Personal Auto', 'Corporate Auto', 'Special Auto']
Length: 3, dtype: str

Unique values in vehicle_class:
<StringArray>
['Four-Door Car',  'Two-Door Car',           'SUV',    'Luxury SUV',
    'Sports Car',    'Luxury Car']
Length: 6, dtype: str

In [ ]:
The state column contains full state names, abbreviations, and inconsistent labels such as Cali, AZ, and WA. The gender column contains values such as F, M, Femal, Male, and female. The education column includes both Bachelor and Bachelors. These categories should be standardized before advanced analysis.

In [30]:
for column in categorical_columns:
    print(f"\nFrequency table for {column}:")
    print(df[column].value_counts(dropna=False))

Frequency table for st:
st
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

Frequency table for gender:
gender
F         457
M         413
NaN       117
Male       39
female     28
Femal      17
Name: count, dtype: int64

Frequency table for education:
education
Bachelor                324
College                 313
High School or Below    296
Master                   94
Doctor                   37
Bachelors                 7
Name: count, dtype: int64

Frequency table for policy_type:
policy_type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

Frequency table for vehicle_class:
vehicle_class
Four-Door Car    576
Two-Door Car     205
SUV              199
Sports Car        57
Luxury SUV        20
Luxury Car        14
Name: count, dtype: int64

In [ ]:
The frequency tables show how customers are distributed across locations, gender categories, education levels, policy types, and vehicle classes. However, inconsistent category labels may divide customers who actually belong to the same group.

In [31]:
df[numerical_columns].describe()

,customer_lifetime_value,income,monthly_premium_auto,total_claim_amount
count,1068.0,1071.000000,1071.000000,1071.000000
mean,793690.259345,39295.701214,193.234360,404.986909
std,643478.410278,30469.427060,1601.190369,293.027260
min,200435.07,0.000000,61.000000,0.382107
25%,403407.995,14072.000000,68.000000,202.157702
50%,588174.235,36234.000000,83.000000,354.729129
75%,896287.1975,64631.000000,109.500000,532.800000
max,5816655.35,99960.000000,35354.000000,2893.239678

In [ ]:
The numerical summary provides the count, mean, standard deviation, minimum, quartiles, and maximum for each numerical variable. The large differences between some maximum values and the upper quartiles suggest that some columns may contain outliers.

In [32]:
numerical_summary = pd.DataFrame({
    "mean": df[numerical_columns].mean(),
    "median": df[numerical_columns].median(),
    "mode": df[numerical_columns].mode().iloc[0],
    "minimum": df[numerical_columns].min(),
    "first_quartile": df[numerical_columns].quantile(0.25),
    "second_quartile": df[numerical_columns].quantile(0.50),
    "third_quartile": df[numerical_columns].quantile(0.75),
    "maximum": df[numerical_columns].max(),
    "range": (
        df[numerical_columns].max()
        - df[numerical_columns].min()
    )
})

numerical_summary

,mean,median,mode,minimum,first_quartile,second_quartile,third_quartile,maximum,range
customer_lifetime_value,793690.259345,588174.235,251459.2,200435.07,403407.995,588174.235,896287.1975,5816655.35,5616220.28
income,39295.701214,36234.0,0.0,0.0,14072.0,36234.0,64631.0,99960.0,99960.0
monthly_premium_auto,193.23436,83.0,65.0,61.0,68.0,83.0,109.5,35354.0,35293.0
total_claim_amount,404.986909,354.729129,321.6,0.382107,202.157702,354.729129,532.8,2893.239678,2892.857571

In [ ]:
Customer lifetime value has a mean higher than its median, indicating positive skew. This means that a smaller number of customers with very high lifetime values increase the average.

Total claim amount also has a mean higher than its median, suggesting that some high claim values pull the average upward.

Monthly premium auto has a maximum value much higher than its median and third quartile. This may indicate an outlier or possible data-entry issue.

Income includes zero values. These may represent customers with no income or missing income recorded as zero.

In [33]:
df[categorical_columns].describe()

            st gender education    policy_type  vehicle_class
count     1071    954      1071           1071           1071
unique       8      5         6              3              6
top     Oregon      F  Bachelor  Personal Auto  Four-Door Car
freq       320    457       324            780            576

In [ ]:
The categorical summary identifies the number of non-missing values, number of unique categories, most frequent category, and frequency of the most common category. These results help identify the dominant customer groups in the dataset.

In [34]:
categorical_summary = pd.DataFrame({
    "non_missing_values": df[categorical_columns].count(),
    "unique_values": df[categorical_columns].nunique(),
    "most_frequent_value": [
        df[column].mode().iloc[0]
        for column in categorical_columns
    ],
    "most_frequent_count": [
        df[column].value_counts().iloc[0]
        for column in categorical_columns
    ]
})

categorical_summary

,non_missing_values,unique_values,most_frequent_value,most_frequent_count
st,1071,8,Oregon,320
gender,954,5,F,457
education,1071,6,Bachelor,324
policy_type,1071,3,Personal Auto,780
vehicle_class,1071,6,Four-Door Car,576

In [ ]:
This table clearly shows the most common category and its frequency for each categorical variable. The results should still be interpreted carefully because some categories use inconsistent spellings or abbreviations.

In [35]:
missing_values = df.isna().sum()

missing_values

customer                       0
st                             0
gender                       117
education                      0
customer_lifetime_value        3
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
dtype: int64

In [ ]:
Some columns contain missing values. Missing data should be considered before conducting further analysis because it may affect statistical results and customer comparisons.

In [36]:
print("Final dataset shape:", df.shape)

print("\nFinal column names:")
print(df.columns.tolist())

print("\nFinal data types:")
print(df.dtypes)

Final dataset shape: (1071, 11)

Final column names:
['customer', 'st', 'gender', 'education', 'customer_lifetime_value', 'income', 'monthly_premium_auto', 'number_of_open_complaints', 'policy_type', 'vehicle_class', 'total_claim_amount']

Final data types:
customer                         str
st                               str
gender                           str
education                        str
customer_lifetime_value      Float64
income                       float64
monthly_premium_auto         float64
number_of_open_complaints        str
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

In [ ]:
The original CSV contained 4,008 rows and 11 columns. Of these, 2,937 rows were completely empty, leaving 1,071 valid customer records after removal.

The column names were standardized and used consistently throughout the analysis. Customer lifetime value was converted from text to numerical data, and the conversion was verified.

The dataset contains both categorical and numerical variables. Several categorical columns contain inconsistent labels, including state, gender, and education. The number of open complaints column also requires additional cleaning because it uses a slash-separated format.

The numerical analysis suggests positive skew in customer lifetime value and total claim amount. Monthly premium auto may contain an unusually high value or outlier. These data-quality issues should be addressed before conducting more advanced customer or insurance analysis.

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [12]:
location_frequency = df["st"].value_counts()

top_5_less_common = location_frequency.sort_values().head(5)

top_5_less_common

st
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [13]:
policy_counts = df["policy_type"].value_counts()

policy_counts

policy_type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

In [14]:
policy_counts.idxmax()

'Personal Auto'

In [15]:
most_sold_policy = policy_counts.idxmax()
number_sold = policy_counts.max()

print("Policy Type:", most_sold_policy)
print("Number of Policies Sold:", number_sold)

Policy Type: Personal Auto
Number of Policies Sold: 780

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [16]:
# Create a DataFrame for Personal Auto customers
personal_auto = df.loc[df["Policy Type"] == "Personal Auto"]

# Create a DataFrame for Corporate Auto customers
corporate_auto = df.loc[df["Policy Type"] == "Corporate Auto"]

# Calculate the average income
personal_avg_income = personal_auto["Income"].mean()
corporate_avg_income = corporate_auto["Income"].mean()

# Print the results
print("Average Income for Personal Auto:", personal_avg_income)
print("Average Income for Corporate Auto:", corporate_avg_income)

KeyError: 'Policy Type'

In [ ]:
if personal_avg_income < corporate_avg_income:
    print("Customers with Personal Auto have a lower average income than customers with Corporate Auto.")
elif personal_avg_income > corporate_avg_income:
    print("Customers with Personal Auto have a higher average income than customers with Corporate Auto.")
else:
    print("Both policy types have the same average income.")

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [ ]:
df["Total Claim Amount"].describe()

In [ ]:
claim_75 = df["Total Claim Amount"].quantile(0.75)

print("75th Percentile:", claim_75)

In [ ]:
high_claim_customers = df[df["Total Claim Amount"] > claim_75]

high_claim_customers

In [ ]:
high_claim_customers.describe()

In [ ]:
high_claim_customers.describe(include=["number"])

In [ ]:
high_claim_customers.describe(include=["object"])

In [ ]:
print("Number of High Claim Customers:", len(high_claim_customers))