# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [3]:
import sys
print(sys.executable)

/Library/Frameworks/Python.framework/Versions/3.13/bin/python3

In [4]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp313-cp313-macosx_11_0_arm64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp313-cp313-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 4.1 MB/s  0:00:03m 3.9 MB/s eta 0:00:01
Installing collected packages: pandas
Successfully installed pandas-3.0.5
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd
print(pd.__version__)

3.0.5

In [2]:
import sys
print(sys.executable)

/Library/Frameworks/Python.framework/Versions/3.13/bin/python3

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [4]:
import pandas as pd

df = pd.read_csv("file1.csv")

In [5]:
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"

try:
    df = pd.read_csv(url)
    print("Dataset loaded from the remote URL.")
except Exception:
    df = pd.read_csv("file1.csv")
    print("Dataset loaded from the local CSV file.")

df.head()

Dataset loaded from the local CSV file.

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [6]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
)

df.columns

Index(['customer', 'st', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='str')

In [7]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 4008
Number of columns: 11

In [8]:
empty_rows = df.isna().all(axis=1).sum()

print("Completely empty rows:", empty_rows)

df = df.dropna(how="all").reset_index(drop=True)

print("Rows after cleaning:", df.shape[0])
print("Columns after cleaning:", df.shape[1])

Completely empty rows: 2937
Rows after cleaning: 1071
Columns after cleaning: 11

In [9]:
empty_rows = df.isna().all(axis=1).sum()

print("Completely empty rows:", empty_rows)

df = df.dropna(how="all").reset_index(drop=True)

print("Rows after cleaning:", df.shape[0])
print("Columns after cleaning:", df.shape[1])

Completely empty rows: 0
Rows after cleaning: 1071
Columns after cleaning: 11

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1071 entries, 0 to 1070
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   str
 1   st                         1071 non-null   str
 2   gender                     954 non-null    str
 3   education                  1071 non-null   str
 4   customer_lifetime_value    1068 non-null   str
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   str
 8   policy_type                1071 non-null   str
 9   vehicle_class              1071 non-null   str
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(3), str(8)
memory usage: 92.2 KB

In [ ]:
The dataset originally contained 4,008 rows and 11 columns. After removing completely empty rows, the dataset contains 1,071 valid customer records.

In [11]:
df.dtypes

customer                         str
st                               str
gender                           str
education                        str
customer_lifetime_value          str
income                       float64
monthly_premium_auto         float64
number_of_open_complaints        str
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

In [12]:
df["customer_lifetime_value"] = (
    df["customer_lifetime_value"]
    .astype("string")
    .str.replace("%", "", regex=False)
)

df["customer_lifetime_value"] = pd.to_numeric(
    df["customer_lifetime_value"],
    errors="coerce"
)

df["customer_lifetime_value"].dtype

Float64Dtype()

In [ ]:
Most columns have appropriate data types. Customer, state, gender, education, policy type, and vehicle class are categorical variables. Customer lifetime value was converted from a string to a numeric variable after removing the percentage symbol. Number of open complaints is still stored as text and should be cleaned before numerical analysis.

In [13]:
unique_counts = df.nunique()

unique_counts

customer                     1071
st                              8
gender                          5
education                       6
customer_lifetime_value      1027
income                        774
monthly_premium_auto          132
number_of_open_complaints       6
policy_type                     3
vehicle_class                   6
total_claim_amount            761
dtype: int64

In [ ]:
Customer is an identifier and therefore contains many unique values. State, gender, education, policy type, and vehicle class are categorical variables that can be used for customer segmentation.

In [14]:
categorical_columns = [
    "st",
    "gender",
    "education",
    "policy_type",
    "vehicle_class"
]

categorical_columns

['st', 'gender', 'education', 'policy_type', 'vehicle_class']

In [15]:
for column in categorical_columns:
    print("\nColumn:", column)
    print("Number of unique values:", df[column].nunique())
    print(df[column].dropna().unique())

Column: st
Number of unique values: 8
<StringArray>
['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali', 'AZ',
 'WA']
Length: 8, dtype: str

Column: gender
Number of unique values: 5
<StringArray>
['F', 'M', 'Femal', 'Male', 'female']
Length: 5, dtype: str

Column: education
Number of unique values: 6
<StringArray>
['Master', 'Bachelor', 'High School or Below', 'College', 'Bachelors',
 'Doctor']
Length: 6, dtype: str

Column: policy_type
Number of unique values: 3
<StringArray>
['Personal Auto', 'Corporate Auto', 'Special Auto']
Length: 3, dtype: str

Column: vehicle_class
Number of unique values: 6
<StringArray>
['Four-Door Car',  'Two-Door Car',           'SUV',    'Luxury SUV',
    'Sports Car',    'Luxury Car']
Length: 6, dtype: str

In [16]:
for column in categorical_columns:
    print("\nColumn:", column)
    print(df[column].value_counts(dropna=False))

Column: st
st
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

Column: gender
gender
F         457
M         413
NaN       117
Male       39
female     28
Femal      17
Name: count, dtype: int64

Column: education
education
Bachelor                324
College                 313
High School or Below    296
Master                   94
Doctor                   37
Bachelors                 7
Name: count, dtype: int64

Column: policy_type
policy_type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

Column: vehicle_class
vehicle_class
Four-Door Car    576
Two-Door Car     205
SUV              199
Sports Car        57
Luxury SUV        20
Luxury Car        14
Name: count, dtype: int64

In [17]:
numerical_columns = [
    "customer_lifetime_value",
    "income",
    "monthly_premium_auto",
    "total_claim_amount"
]

numerical_columns

['customer_lifetime_value',
 'income',
 'monthly_premium_auto',
 'total_claim_amount']

In [18]:
numerical_ranges = pd.DataFrame({
    "Minimum": df[numerical_columns].min(),
    "Maximum": df[numerical_columns].max(),
    "Range": df[numerical_columns].max() - df[numerical_columns].min()
})

numerical_ranges

                           Minimum      Maximum        Range
customer_lifetime_value  200435.07   5816655.35   5616220.28
income                         0.0      99960.0      99960.0
monthly_premium_auto          61.0      35354.0      35293.0
total_claim_amount        0.382107  2893.239678  2892.857571

In [19]:
numerical_summary = pd.DataFrame({
    "Mean": df[numerical_columns].mean(),
    "Median": df[numerical_columns].median(),
    "Mode": df[numerical_columns].mode().iloc[0],
    "Standard Deviation": df[numerical_columns].std(),
    "Minimum": df[numerical_columns].min(),
    "First Quartile": df[numerical_columns].quantile(0.25),
    "Second Quartile": df[numerical_columns].quantile(0.50),
    "Third Quartile": df[numerical_columns].quantile(0.75),
    "Maximum": df[numerical_columns].max()
})

numerical_summary

,Mean,Median,Mode,Standard Deviation,Minimum,First Quartile,Second Quartile,Third Quartile,Maximum
customer_lifetime_value,793690.259345,588174.235,251459.2,643478.410278,200435.07,403407.995,588174.235,896287.1975,5816655.35
income,39295.701214,36234.0,0.0,30469.42706,0.0,14072.0,36234.0,64631.0,99960.0
monthly_premium_auto,193.23436,83.0,65.0,1601.190369,61.0,68.0,83.0,109.5,35354.0
total_claim_amount,404.986909,354.729129,321.6,293.02726,0.382107,202.157702,354.729129,532.8,2893.239678

In [ ]:
Customer lifetime value and total claim amount show considerable variation among customers. Income ranges from 0 to nearly 100,000, while monthly premium auto contains an unusually high maximum value, suggesting a possible outlier or data entry error.

In [ ]:
df[numerical_columns].describe()

In [20]:
categorical_summary = df[categorical_columns].describe()

categorical_summary

            st gender education    policy_type  vehicle_class
count     1071    954      1071           1071           1071
unique       8      5         6              3              6
top     Oregon      F  Bachelor  Personal Auto  Four-Door Car
freq       320    457       324            780            576

In [21]:
categorical_results = pd.DataFrame({
    "Number of Unique Values": df[categorical_columns].nunique(),
    "Most Frequent Value": [
        df[column].mode().iloc[0]
        for column in categorical_columns
    ],
    "Frequency": [
        df[column].value_counts().iloc[0]
        for column in categorical_columns
    ]
})

categorical_results

               Number of Unique Values Most Frequent Value  Frequency
st                                   8              Oregon        320
gender                               5                   F        457
education                            6            Bachelor        324
policy_type                          3       Personal Auto        780
vehicle_class                        6       Four-Door Car        576

In [ ]:
Personal Auto is the most common policy type. Four Door Car is the most common vehicle class. Some categorical columns contain inconsistent values, such as different spellings for education, gender, and state names, which should be standardized before advanced analysis.

In [22]:
print("Final Dataset Shape:")
print(df.shape)

print("\nMissing Values:")
print(df.isna().sum())

print("\nData Types:")
print(df.dtypes)

Final Dataset Shape:
(1071, 11)

Missing Values:
customer                       0
st                             0
gender                       117
education                      0
customer_lifetime_value        3
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
dtype: int64

Data Types:
customer                         str
st                               str
gender                           str
education                        str
customer_lifetime_value      Float64
income                       float64
monthly_premium_auto         float64
number_of_open_complaints        str
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [22]:
location_frequency = df["ST"].value_counts()

top_5_less_common = location_frequency.sort_values().head(5)

top_5_less_common

ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [23]:
policy_counts = df["Policy Type"].value_counts()

policy_counts

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

In [24]:
policy_counts.idxmax()

'Personal Auto'

In [25]:
most_sold_policy = policy_counts.idxmax()
number_sold = policy_counts.max()

print("Policy Type:", most_sold_policy)
print("Number of Policies Sold:", number_sold)

Policy Type: Personal Auto
Number of Policies Sold: 780

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [26]:
# Create a DataFrame for Personal Auto customers
personal_auto = df.loc[df["Policy Type"] == "Personal Auto"]

# Create a DataFrame for Corporate Auto customers
corporate_auto = df.loc[df["Policy Type"] == "Corporate Auto"]

# Calculate the average income
personal_avg_income = personal_auto["Income"].mean()
corporate_avg_income = corporate_auto["Income"].mean()

# Print the results
print("Average Income for Personal Auto:", personal_avg_income)
print("Average Income for Corporate Auto:", corporate_avg_income)

Average Income for Personal Auto: 38180.69871794872
Average Income for Corporate Auto: 41390.31196581197

In [27]:
if personal_avg_income < corporate_avg_income:
    print("Customers with Personal Auto have a lower average income than customers with Corporate Auto.")
elif personal_avg_income > corporate_avg_income:
    print("Customers with Personal Auto have a higher average income than customers with Corporate Auto.")
else:
    print("Both policy types have the same average income.")

Customers with Personal Auto have a lower average income than customers with Corporate Auto.

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [28]:
df["Total Claim Amount"].describe()

count    1071.000000
mean      404.986909
std       293.027260
min         0.382107
25%       202.157702
50%       354.729129
75%       532.800000
max      2893.239678
Name: Total Claim Amount, dtype: float64

In [29]:
claim_75 = df["Total Claim Amount"].quantile(0.75)

print("75th Percentile:", claim_75)

75th Percentile: 532.8

In [30]:
high_claim_customers = df[df["Total Claim Amount"] > claim_75]

high_claim_customers

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
17,OE15005,Cali,NaN,College,394524.16,28855.0,101.0,1/0/00,Personal Auto,SUV,647.442031
23,TZ98966,Nevada,NaN,Bachelor,245019.10,0.0,73.0,1/3/00,Corporate Auto,Four-Door Car,554.376763
26,US89481,California,NaN,Bachelor,394637.21,0.0,111.0,1/0/00,Personal Auto,Four-Door Car,799.200000
...,...,...,...,...,...,...,...,...,...,...,...
1059,YG44474,Oregon,M,College,1401472.13,54193.0,117.0,1/0/00,Corporate Auto,SUV,720.752945
1061,RY92647,Cali,F,Bachelor,1050677.17,0.0,92.0,1/0/00,Personal Auto,Four-Door Car,546.524896
1068,GS98873,Arizona,F,Bachelor,323912.47,16061.0,88.0,1/0/00,Personal Auto,Four-Door Car,633.600000
1069,CW49887,California,F,Master,462680.11,79487.0,114.0,1/0/00,Special Auto,SUV,547.200000
1070,MY31220,California,F,College,899704.02,54230.0,112.0,1/0/00,Personal Auto,Two-Door Car,537.600000

In [31]:
high_claim_customers.describe()

,Customer Lifetime Value,Income,Monthly Premium Auto,Total Claim Amount
count,2.640000e+02,264.000000,264.000000,264.000000
mean,9.086868e+05,23677.344697,165.193182,782.228263
std,6.387678e+05,27013.483721,623.930992,292.751640
min,2.287597e+05,0.000000,63.000000,537.600000
25%,4.723958e+05,0.000000,99.000000,606.521741
50%,7.781768e+05,18807.000000,114.000000,679.597985
75%,1.054430e+06,42423.750000,133.250000,851.400000
max,3.844586e+06,99316.000000,10202.000000,2893.239678

In [32]:
high_claim_customers.describe(include=["number"])

,Customer Lifetime Value,Income,Monthly Premium Auto,Total Claim Amount
count,2.640000e+02,264.000000,264.000000,264.000000
mean,9.086868e+05,23677.344697,165.193182,782.228263
std,6.387678e+05,27013.483721,623.930992,292.751640
min,2.287597e+05,0.000000,63.000000,537.600000
25%,4.723958e+05,0.000000,99.000000,606.521741
50%,7.781768e+05,18807.000000,114.000000,679.597985
75%,1.054430e+06,42423.750000,133.250000,851.400000
max,3.844586e+06,99316.000000,10202.000000,2893.239678

In [33]:
high_claim_customers.describe(include=["object"])

/var/folders/3_/6lgqyskd5v55bylpxy1jbmzr0000gn/T/ipykernel_91483/4154236068.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  high_claim_customers.describe(include=["object"])

,Customer,ST,GENDER,Education,Number of Open Complaints,Policy Type,Vehicle Class
count,264,264,238,264,264,264,264
unique,264,7,5,5,6,3,6
top,QZ44356,Oregon,F,Bachelor,1/0/00,Personal Auto,SUV
freq,1,90,115,85,206,191,101

In [34]:
print("Number of High Claim Customers:", len(high_claim_customers))

Number of High Claim Customers: 264